version: '3.4'

services:
  database:
    image: mysql:latest
    volumes:
        - dbdata:/var/lib/mysql
    restart: always
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: leaderboard
        MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  leaderboardservice:
    image: ${DOCKER_REGISTRY-}leaderboardservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42430:42430"

volumes:
  dbdata: